/********* Drop the FamousShips Table ******/
DROP TABLE  FamousShips;


/******** Create the FamousShips Table *****/
CREATE TABLE FamousShips(
	Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	Name varchar(50),
    Nickname varchar(50),
	Captain varchar(50),
	Description varchar(1024),
	Type varchar(50)
/*   , CONSTRAINT PK_FamousShips PRIMARY KEY (Id) */
);

