package com.fidelity.birthday;

import java.time.LocalDate;

/*
 * Here are some sample birthdays (ignore the uncertainty)
 * 
 * Alexander Hamilton - 11 Jan 1757 (or possibly 1755!) - Charlestown, Saint Kitts and Nevis
 * Winston Churchill - 30 Nov 1874 - Blenheim Palace, Woodstock, United Kingdom
 * Jawaharlal Nehru - 14 Nov 1889 - Allahabad, India
 * Nelson Mandela - 18 July 1918 - Mvezo, South Africa
 * Charlemagne - 2 Apr 742 (probably) - Aachen, Germany (possibly!)
 */
public class Birthday {
	public LocalDate getDateOfBirth() {
		return dateOfBirth;
	}

	public String getPlaceOfBirth() {
		return placeOfBirth;
	}

	private LocalDate dateOfBirth;
	private String placeOfBirth;
	
	// auto-generated by Eclipse from here
	
	public Birthday(LocalDate dateOfBirth, String placeOfBirth) {
		super();
		this.dateOfBirth = dateOfBirth;
		this.placeOfBirth = placeOfBirth;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dateOfBirth == null) ? 0 : dateOfBirth.hashCode());
		result = prime * result + ((placeOfBirth == null) ? 0 : placeOfBirth.hashCode());
		return result;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Birthday other = (Birthday) obj;
		if (dateOfBirth == null) {
			if (other.dateOfBirth != null)
				return false;
		} else if (!dateOfBirth.equals(other.dateOfBirth))
			return false;
		if (placeOfBirth == null) {
			if (other.placeOfBirth != null)
				return false;
		} else if (!placeOfBirth.equals(other.placeOfBirth))
			return false;
		return true;
	}
	
	@Override
	public String toString() {
		return "Birthday [dateOfBirth=" + dateOfBirth + ", placeOfBirth=" + placeOfBirth + "]";
	}

	
}
