--
-- Table structure for table `country_region`
--

DROP TABLE CITY;
DROP TABLE COUNTRY_REGION;		

CREATE TABLE COUNTRY_REGION (
	ID NUMBER(10) PRIMARY KEY,
	COUNTRY_CODE VARCHAR2(2) NOT NULL,
	REGION_CODE VARCHAR2(2) NOT NULL
);

--
-- Table structure for table `city`
--

CREATE TABLE CITY (
	ID NUMBER(10) PRIMARY KEY,
	CITY VARCHAR2(100) NOT NULL,
	COUNTRY_REGION_ID NUMBER(10) NOT NULL,
	LAT NUMBER(9, 6) NOT NULL,
	LON NUMBER(9, 6) NOT NULL,
	CONSTRAINT FK_CITY_COUNTRY_REGION FOREIGN KEY (COUNTRY_REGION_ID) REFERENCES COUNTRY_REGION(ID)
);
