CREATE TABLE CP_CLIENT (
    CLIENTID VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    POSTALCODE VARCHAR(20) NOT NULL,
    PRIMARY KEY (CLIENTID),
    UNIQUE (EMAIL)
);

CREATE TABLE CP_CLIENT_AUTH (
    CLIENTID VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    PRIMARY KEY (CLIENTID),
    UNIQUE (EMAIL),
    FOREIGN KEY (CLIENTID) REFERENCES CP_CLIENT (CLIENTID)
);

CREATE TABLE CP_CLIENT_IDENTIFICATION (
    CLIENTID VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (CLIENTID, TYPE),
    FOREIGN KEY (CLIENTID) REFERENCES CP_CLIENT (CLIENTID)
);

CREATE TABLE CP_INVESTMENT_PREFERENCE (
    CLIENTID INT NOT NULL,
    INVESTMENTPURPOSE VARCHAR(1000) NOT NULL,
    INVESTMENTLENGTH VARCHAR(1000) NOT NULL,
    RISKTOLERANCE VARCHAR(1000) NOT NULL,
    INCOMECATEGORY VARCHAR(1000) NOT NULL,
    UNIQUE (CLIENTID),
    PRIMARY KEY (CLIENTID, TYPE),
    FOREIGN KEY (CLIENTID) REFERENCES CP_CLIENT (CLIENTID)
);

CREATE TABLE CP_ORDER (
    ORDERID VARCHAR(255),
    INSTRUMENTID VARCHAR(255),
    QUANTITY NUMERIC NOT NULL,
    TARGETPRICE NUMERIC NOT NULL,
    DIRECTION CHAR(1) CHECK (DIRECTION IN ('B', 'S')),
    CLIENTID VARCHAR(255),
    PRIMARY KEY (ORDERID),
    FOREIGN KEY (CLIENTID) REFERENCES CP_CLIENT (CLIENTID)
);

CREATE TABLE CP_TRADE (
    TRADEID VARCHAR(255),
    INSTRUMENTID VARCHAR(255),
    QUANTITY NUMERIC NOT NULL,
    EXECUTIONPRICE NUMERIC NOT NULL,
    DIRECTION CHAR(1) CHECK (DIRECTION IN ('B', 'S')),
    CLIENTID VARCHAR(255),
    ORDERID VARCHAR(255),
    CASHVALUE NUMERIC NOT NULL,
    PRIMARY KEY (TRADEID),
    FOREIGN KEY (CLIENTID) REFERENCES CP_CLIENT (CLIENTID),
    FOREIGN KEY (ORDERID) REFERENCES CP_ORDER (ORDERID)
);




