


insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Chennai', 'India', 'Chennai', -7.783297, 110.363649);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Kanyakumari', 'India', 'Kanyakumari', 54.7124613, 44.8379034);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Visakhapatnam', 'India', 'Visakhapatnam', 8.8443024, -79.8548823);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Mumbai', 'India', 'Mumbai', 32.117935, 121.009708); 
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Dublin', 'Ireland', 'Dublin', 15.4566044, -91.8808763);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Galway', 'Ireland', 'Galway', 38.560256, 69.0165511);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Dingle', 'Ireland', 'Dingle', 49.387383, 1.0839961);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Belmullet', 'Ireland', 'Belmullet', -8.8828551, -36.4968966);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Bangor', 'Ireland', 'Belfast', 40.23921, 116.12895);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Wilmington', 'United States', 'Wilmington', -7.6077557, 112.243026);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Nags Head', 'United States', 'Kitty Hawk', 0.7013707, 32.9029088);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('Ports Mouth', 'United States', 'Pamilco', 48.7277622, 100.7724281);
insert into SEA_PORTS (port_name, country, location, latitude, longitude) values ('South', 'United States', 'Myrtle', 61.9581691, 14.8300464);







insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Sunscreen', 'Diving', 'Mexico', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Nystatin', 'Diving', 'China', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Medroxyprogesterone Acetate', 'Racing', 'Mongolia', 11);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Mirtazapine', 'Racing', 'Brazil', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('OXYSPORUM VASINFECTUM', 'Diving', 'Ukraine', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Azithromycin', 'Racing', 'China', 2);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('PROMETHAZINE HYDROCHLORIDE', 'Fishing', 'Albania', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('ARTEMISIA VULGARIS POLLEN', 'Sailing', 'Sweden', 11);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('tilmanocept', 'Fishing', 'China', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Diovan HCT', 'Fishing', 'China', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('CRESTOR', 'Racing', 'Ukraine', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Lavender Hand', 'Motor Yacht', 'Philippines', 11);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Doxycycline', 'Fishing', 'Spain', 1);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Metoprolol Tartrate', 'Sailing', 'China', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Moore Medical MooreBrand', 'Fishing', 'Argentina', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('OXYGEN', 'Catamaran', 'China', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Flavoxate Hydrochloride', 'Diving', 'Luxembourg', 10);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('SKELAXIN', 'Motor Yacht', 'United Arab Emirates', 8);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Ranitidine Hydrochloride', 'Sailing', 'Colombia', 7);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Proctofoam', 'Catamaran', 'Sweden', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Aurum Prunus', 'Catamaran', 'Tajikistan', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Divalproex Sodium', 'Sailing', 'Namibia', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Iman Time Control Oil', 'Super Yacht', 'Mexico', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('ciprofloxacin', 'Super Yacht', 'Honduras', 1);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Omnipaque', 'Fishing', 'Indonesia', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('ENALAPRIL MALEATE', 'Diving', 'Bolivia', 11);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Citrus Basil', 'Sailing', 'Mongolia', 5);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Bald Cypress', 'Diving', 'Czech Republic', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Paclitaxel', 'Diving', 'Sweden', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Doxycycline Hyclate', 'Fishing', 'Bosnia and Herzegovina', 7);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('SAPHRIS', 'Super Yacht', 'Bosnia and Herzegovina', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Female Tonic', 'Motor Yacht', 'Israel', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('COUMADIN', 'Fishing', 'Philippines', 5);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Motion Sickness', 'Fishing', 'Ethiopia', 7);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Lyrica', 'Fishing', 'Indonesia', 11);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Oxycodone Hydrochloride', 'Super Yacht', 'China', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Isradipine', 'Fishing', 'Brazil', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Pulsatilla', 'Racing', 'Rwanda', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Bupropion Hydrochloride', 'Super Yacht', 'Indonesia', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('potassium chloride', 'Motor Yacht', 'Russia', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Bupropion Hydrocloride', 'Fishing', 'Philippines', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Bystolic', 'Fishing', 'Brazil', 8);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Metoprolol Tartrate', 'Catamaran', 'Mexico', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Covergirl Outlast Stay Fabulous 3in1 Foundation', 'Fishing', 'Peru', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Slash Pine', 'Diving', 'Thailand', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('ATORVASTATIN CALCIUM', 'Fishing', 'Panama', 10);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Lambs Quarters Pollen', 'Sailing', 'Cuba', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('IQueen CCC Light', 'Super Yacht', 'China', 1);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('pravastatin sodium', 'Fishing', 'Sweden', 11);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Bang Er Jie ', 'Fishing', 'China', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Restorative Day Moisture SPF 15', 'Catamaran', 'Bangladesh', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Aveda Active Composition', 'Diving', 'France', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Topiramate', 'Super Yacht', 'Indonesia', 8);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Dove', 'Racing', 'China', 5);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Dicyclomine', 'Fishing', 'Sri Lanka', 10);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Rasuvo', 'Sailing', 'Brazil', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Donnatal', 'Racing', 'China', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Orajel for Cold Sores', 'Racing', 'Ukraine', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Ferrlecit', 'Super Yacht', 'Ukraine', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Cold - Sinus', 'Diving', 'Ethiopia', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('FENTANYL CITRATE', 'Catamaran', 'Portugal', 10);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('mesna', 'Super Yacht', 'Mongolia', 8);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Antiseptic', 'Motor Yacht', 'Japan', 10);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Desloratadine', 'Catamaran', 'Nigeria', 1);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Doxazosin', 'Fishing', 'Venezuela', 11);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('SENSODYNE', 'Catamaran', 'Portugal', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('CoughZolo', 'Fishing', 'China', 13);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Zoloft', 'Catamaran', 'China', 5);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Day Night Cold and Flu', 'Fishing', 'Russia', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Clonazepam', 'Racing', 'Portugal', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Allergy and Stuffy Nose', 'Diving', 'Poland', 1);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Furosemide', 'Catamaran', 'Indonesia', 8);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Alcortin A', 'Motor Yacht', 'China', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Fentanyl Citrate', 'Super Yacht', 'Indonesia', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Losartan Potassium', 'Fishing', 'Indonesia', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Sucralfate', 'Super Yacht', 'China', 5);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Atenolol', 'Super Yacht', 'Indonesia', 5);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Nifedipine', 'Fishing', 'Indonesia', 2);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Nitrogen', 'Racing', 'China', 2);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('VETERNIARY FIRST AID', 'Fishing', 'Pakistan', 5);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Synthroid', 'Super Yacht', 'Vietnam', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Flurazepam', 'Fishing', 'Philippines', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Stomach Distress', 'Racing', 'Brazil', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Western Family', 'Motor Yacht', 'Peru', 12);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Dry Cough', 'Fishing', 'France', 10);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('NESTABS', 'Catamaran', 'Sweden', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Methimazole', 'Fishing', 'Germany', 4);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Rhodotorula mucilaginosa', 'Motor Yacht', 'Netherlands', 8);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Neutrogena SkinClearing', 'Racing', 'Indonesia', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Benztropine Mesylate', 'Super Yacht', 'Russia', 8);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('SMART SENSE', 'Catamaran', 'Portugal', 9);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Synthroid', 'Motor Yacht', 'Greece', 7);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('topcare nite', 'Catamaran', 'Mexico', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Pramosone E', 'Catamaran', 'Honduras', 2);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Ceftriaxone Sodium', 'Sailing', 'China', 1);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Symmetry Foa', 'Sailing', 'China', 3);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('ATORVASTATIN CALCIUM', 'Fishing', 'Indonesia', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Docusate Sodium', 'Racing', 'Brazil', 1);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('smart sense', 'Diving', 'Portugal', 6);
insert into vessels (vessel_name, vessel_type, vessel_country, vessel_port) values ('Torsemide', 'Fishing', 'Portugal', 3);
